---
title: "STAT 293 Final Project EDA"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(tidyverse)
library(survival)
```

```{r}
# load dataset
heart_data <- read.csv(file.choose())
```

# Baselline table

```{r}
# clean and label the dataset to prep for EDA
heart_data <- heart_data %>%
  mutate(num = as.character(num),
         # regroup by survival status
         status = factor(status,
                         levels = c(0, 1),
                         labels = c("Lost at follow-up",
                                    "Died")),
         # factor key categorical covariates 
         sex = factor(sex,
                      levels = c(0, 1),
                      labels = c("Male",
                                 "Female")),
         prenyha = factor(prenyha,
                          levels = c(1, 3),
                          labels = c("I/II",
                                     "III/IV")),
         lvh = factor(lvh),
         redo = factor(redo),
         dm = factor(dm),
         lv = factor(lv,
                     levels = c(1, 2, 3),
                     labels = c("good",
                                "moderate",
                                "poor")),
         
    # set stentless as reference level for valve type
    hs = factor(hs) %>% fct_relevel("Stentless valve")
  )

# one row per patient 
base <- heart_data %>%
  distinct(num,
           .keep_all = TRUE)
```

```{r}
# checking for missingness 
vars <- c("status", "log.lvmi", "age", "bsa", "lvh", "prenyha", "redo", "lv",
          "dm", "hs", "sex")

missingness <- base %>%
  summarise(across(all_of(vars),
                   ~ sum(is.na(.x)))) %>%
  tidyr::pivot_longer(everything(),
                      names_to = "variable",
                      values_to = "n_missing") %>%
  arrange(desc(n_missing))

missingness
```

```{r}
# choose numeric covariates
num_vars <- c("log.lvmi", "age", "bsa")  

# numerical summaries
base %>%
  group_by(status) %>%
  dplyr::summarise(n = n(),
                   across(all_of(num_vars),
                          list(mean = ~ mean(.x, na.rm = TRUE),
                               sd = ~ sd(.x, na.rm = TRUE),
                               median = ~ median(.x, na.rm = TRUE)),
                          .names = "{.col}_{.fn}"))
```

```{r}
# choose categorical covariates
cat_vars <- c("sex", "hs", "dm", "lv", "redo", "prenyha")

base %>%
  dplyr::select(status,
                all_of(cat_vars)) %>%
  tidyr::pivot_longer(-status,
                      names_to = "var",
                      values_to = "value") %>%
  count(status, var, value) %>%
  group_by(status, var)
```

# Boxplots of numerical baselines covariates by survival status 

```{r}
status_cols <- c("Lost at follow-up" = "#262686",
                 "Died" = "darkred")

base %>%
  dplyr::select(status,
         all_of(num_vars)) %>%
  pivot_longer(-status,
               names_to = "var",
               values_to = "value") %>%
  ggplot(aes(status,
             value,
             fill = status)) +
  geom_boxplot(outlier.alpha = 0.3) +
  facet_wrap(~var,
             scales = "free_y",
             ncol = 3) +
  scale_fill_manual(values = status_cols) +
  labs(x = "Survival status") +
  theme(legend.position = "none")
```

# Bar plots of categorical baselines covariates by survival status

```{r}
base %>%
  dplyr::select(status,
         all_of(cat_vars)) %>%
  pivot_longer(-status,
               names_to = "var",
               values_to = "value") %>%
  ggplot(aes(x = value,
             fill = status)) +
  geom_bar(position = "fill") +
  facet_wrap(~var,
             ncol = 3,
             scales = "free_x") +
  scale_fill_manual(values = status_cols) +
  labs(y = "Proportion",
       fill = "Survival status") +
  theme(axis.text.x = element_text(angle = 10, hjust = 0.5))
```

# Overall survival status curve

```{r}
surv_obj <- Surv(base$fuyrs,
                 base$status == "Died")

fit <- survfit(surv_obj ~ 1, data = base)

plot(fit,
     col = "darkred",
     lwd = 2,
     xlab = "Time since surgery (years)",
     ylab = "Survival probability")
```

# Compare log(lvmi) rate of change over time by survival status

```{r,message=FALSE,warning=FALSE}
# longitudinal smoother by status
ggplot(heart_data,
       aes(time,
           log.lvmi,
           color = status)) +
  geom_smooth(se = TRUE) +
  scale_color_manual(values = c("Lost at follow-up" = "#262686",
                                "Died" = "darkred")) +
  labs(title = "Comparison of log(LVMI) Trajectories over Time by Survival Status",
       x = "Follow-up time (years)",
       y = "log(LVMI)",
       fill = "Survival status") +
  theme(legend.position = "top")
```

# Sphagetti plot of 

```{r}
ggplot(heart_data,
       aes(x = time,
           y = log.lvmi,
           group = num)) +
  geom_line(alpha = 0.3) +
  labs(title = "Spaghetti Plot of log(LVMI) Trajectories",
       x = "Follow-up Time (years)",
       y = "log(LVMI)") +
  theme_minimal()
```
